import { Sidebar } from "@/components/sidebar";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider";
import { buttonVariants } from "@/components/ui/button";
import Link from "next/link";
import "react-toastify/dist/ReactToastify.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
          <Sidebar />
          {/* <main className="p-6 grid grid-cols-2 relative lg:ml-[224px] gap-4"> */}
          <div className="lg:ml-56">
            <header className="flex justify-end border-b border-border p-4">
              <Link className={buttonVariants()} href="/posts/create">
                Criar Post
              </Link>
            </header>
            <main className="p-6">{children}</main>
            {/* <Editor /> */}
            {/* <CodeEditor /> */}
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
