import "@uploadthing/react/styles.css";
import "./globals.css";
import "react-toastify/dist/ReactToastify.css";

import { Sidebar } from "@/components/sidebar";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider";
import { buttonVariants } from "@/components/ui/button";
import Link from "next/link";
import { Providers } from "@/components/toaster-provider";
import prisma from "@/lib/prisma";
import getCurrentUser from "@/actions/get-current-user";
import { SignInButton } from "@/components/sign-in-button";
import { OpenSidebarButton } from "@/components/open-sidebar-button";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const currentUser = await getCurrentUser();

  const posts = await prisma.post.findMany({
    where: {
      status: "approved",
    },
    select: {
      id: true,
      name: true,
      category: true,
    },
  });

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <Providers />
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
          <Sidebar posts={posts} />
          <div className="lg:ml-56">
            <header className="flex justify-between lg:justify-end border-b border-border p-4">
              <OpenSidebarButton />
              {currentUser ? (
                <div className="flex gap-2">
                  {currentUser.role === "admin" && (
                    <Link
                      className={buttonVariants({
                        size: "lg",
                        variant: "outline",
                      })}
                      href="/admin"
                    >
                      Administração
                    </Link>
                  )}
                  <Link
                    className={buttonVariants({ size: "lg" })}
                    href="/posts/create"
                  >
                    Criar Post
                  </Link>
                </div>
              ) : (
                <SignInButton />
              )}
            </header>
            <main className="p-6">{children}</main>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
